services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:lts
    restart: always
    labels:
      homepage.group: "Management"
      homepage.name: "Portainer"
      homepage.icon: "portainer.png"
      homepage.href: "https://portainer.${DOMAIN}"
      homepage.description: "Container Management"
      traefik.enable: "true"
      traefik.http.routers.portainer.rule: "Host(`portainer.${DOMAIN}`)"
      traefik.http.routers.portainer.entrypoints: "https"
      traefik.http.routers.portainer.tls.certresolver: "cloudflare"
      traefik.http.services.portainer.loadbalancer.server.url: "https://${HOST_IP}:9443"
      traefik.http.services.portainer.loadbalancer.serverstransport: "insecure@file"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - 9443:9443
      - 8000:8000  # Remove if you do not intend to use Edge Agents

volumes:
  portainer_data:
    name: portainer_data

networks:
  default:
    name: kendricklab 
