version: "3"

networks:
  gitea:
    external: false

services:
  server:
    image: docker.gitea.com/gitea:1.25.2
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    labels:
      homepage.group: "Version Control"
      homepage.name: "Gitea"
      homepage.icon: "gitea.png"
      homepage.href: "http://gitea:3000"
      homepage.description: "Git Server"
    networks:
      - gitea
    volumes:
      - ${CONFIG_ROOT}/gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "222:22"
